# Generated by Django 4.2 on 2023-05-21 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slogan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100)),
                ('slogan', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='misyon',
            name='slogan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newApp.slogan'),
        ),
        migrations.AddField(
            model_name='vizyon',
            name='slogan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newApp.slogan'),
        ),
    ]
