# Generated by Django 4.2 on 2023-05-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0002_slogan_misyon_slogan_vizyon_slogan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('resim', models.ImageField(blank=True, null=True, upload_to='sube/', verbose_name='Şube Resmi (Opsiyonel)')),
            ],
        ),
        migrations.AlterField(
            model_name='hizmet',
            name='aciklama',
            field=models.TextField(blank=True, verbose_name='Açıklama (Opsiyonel)'),
        ),
    ]
