# Generated by Django 4.2 on 2023-05-21 18:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0003_sube_alter_hizmet_aciklama'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hakkimizda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100)),
                ('icerik', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='hizmet',
            name='aciklama',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Açıklama (Opsiyonel)'),
        ),
        migrations.AlterField(
            model_name='misyon',
            name='icerik',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='slogan',
            name='slogan',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='vizyon',
            name='icerik',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
