# Generated by Django 4.2 on 2023-05-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0005_slider_ispublish'),
    ]

    operations = [
        migrations.AddField(
            model_name='hizmet',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, null=True, unique=True),
        ),
    ]
