# Generated by Django 4.2 on 2023-05-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0007_slider_aciklama'),
    ]

    operations = [
        migrations.AddField(
            model_name='hakkimizda',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='hakkimizda/'),
        ),
    ]
