# Generated by Django 4.2 on 2023-05-21 19:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0008_hakkimizda_resim'),
    ]

    operations = [
        migrations.AddField(
            model_name='hakkimizda',
            name='ozet',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Özet (Anasayfada Çıkacak Olan Kısım)'),
        ),
    ]
