# Generated by Django 4.2 on 2023-05-21 19:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0009_hakkimizda_ozet'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='aciklama',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='slogan',
            name='slogan',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
