# Generated by Django 4.2 on 2023-05-21 19:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0010_program_aciklama_alter_slogan_slogan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hizmetler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100)),
                ('aciklama', ckeditor.fields.RichTextField(blank=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmetlerimiz Anasayfa',
            },
        ),
    ]
