# Generated by Django 4.2 on 2023-05-21 20:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0011_hizmetler'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeri',
            name='aciklama',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
    ]
