# Generated by Django 4.2 on 2023-05-21 07:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('newApp', '0003_sube_alter_hizmet_aciklama'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egitim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('baslik', models.CharField(max_length=100)),
                ('aciklama', models.TextField(blank=True)),
                ('resim', models.ImageField(upload_to='egitim_resimleri', verbose_name='Eğitim Resmi')),
                ('baslama_tarihi', models.DateField()),
                ('sure', models.CharField(max_length=100)),
                ('fiyat', models.IntegerField()),
                ('slug', models.SlugField(editable=False, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hizmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.hizmet')),
                ('sube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.sube')),
            ],
            options={
                'verbose_name': 'Eğitim',
                'verbose_name_plural': 'Eğitimler',
                'ordering': ['-created_at'],
            },
        ),
    ]
