# Generated by Django 4.2 on 2023-05-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egitimler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='egitim',
            name='isPublish',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
